config/routes.rb
Rails.application.routes.draw do
  root "units#index"

  resources :units
  resources :locations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/equip.rb
class Equip < ApplicationRecord
  belongs_to :unit
end

app/models/location.rb
class Location < ApplicationRecord
    validates :name, presence: true
    
    after_create :update_defaults
    
    def update_defaults
        if (self.name == "Tornire")
            update(shop: "potion, basic bow, basic wand, basic sword", 
                bank: "deposit, withdraw", 
                quest: "defeat coyote")
        end
    end
end

app/models/unit.rb
class Unit < ApplicationRecord
    has_one :equips

    validates :name, presence: true
    validates :classtype, presence: true
    validates :gender, presence: true

    after_create :update_defaults
    
    def update_defaults
        if (self.classtype == "warrior")
            update(char_lvl: 1, char_xp: 0, char_atp: 30, char_def: 50, char_eva: 30, char_hp: 100, char_tp: 10, gold: 100, locate: "Tornire")
        elsif (self.classtype == "ranger")
            update(char_lvl: 1, char_xp: 0, char_atp: 40, char_def: 30, char_eva: 40, char_hp: 80, char_tp: 20, gold: 100, locate: "Tornire")
        else
            update(char_lvl: 1, char_xp: 0, char_atp: 50, char_def: 20, char_eva: 40, char_hp: 60, char_tp: 30, gold: 100, locate: "Tornire")
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/equips_controller.rb
class EquipsController < ApplicationController
    def create
        @unit = Unit.find(params[:unit_id])
        @equip = @unit.equips.create(equip_params)
        redirect_to unit_path(@unit)
    end

    private
        def equip_params
            params.require(:equip).permit(:helm, :armor, :accessory, :weapon)
        end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    def index
        @locations = Location.all
    end
    
    def show
        @location = Location.find(params[:id])
    end

    def edit
      @location = Location.find(params[:id])
    end

    def create
        @location = Location.new(location_params)
    
        if @location.save
          redirect_to @location
        else
          render :new, status: :unprocessable_entity
        end
      end

    def new
        @location = Location.new
    end

    def destroy
      @location = Location.find(params[:id])
      @location.destroy
  
      redirect_to root_path, status: :see_other
    end

    private
        def location_params
            params.require(:location).permit(:name)
        end
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  def index
    @units = Unit.all
  end

  def show
    @unit = Unit.find(params[:id])
  end

  def new
    @unit = Unit.new
  end

  def create
    @unit = Unit.new(unit_params)

    if @unit.save
      redirect_to @unit
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @unit = Unit.find(params[:id])
  end

  def update
    @unit = Unit.find(params[:id])

    if @unit.update(unit_params)
      redirect_to @unit
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def unit_params
      params.require(:unit).permit(:name, :classtype, :gender)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/equips_helper.rb
module EquipsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/equips/_equip.html.erb
<p>
  <strong>Helm:</strong>
  <%= equip.helm %>
</p>

<p>
  <strong>Armor:</strong>
  <%= equip.armor %>
</p>

<p>
  <strong>Accessory:</strong>
  <%= equip.accessory %>
</p>

<p>
  <strong>Weapon:</strong>
  <%= equip.weapon %>
</p>

app/views/equips/_form.html.erb
<%= form_with model: [ @unit, @unit.equips.build ] do |form| %>
  <p>
    <%= form.label :helm %><br>
    <%= form.text_field :helm %>
  </p>
  <p>
    <%= form.label :armor %><br>
    <%= form.text_area :armor %>
  </p>
  <p>
    <%= form.label :accessory %><br>
    <%= form.text_area :accessory %>
  </p>
  <p>
    <%= form.label :weapon %><br>
    <%= form.text_area :weapon %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LotF</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with model: @location do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @location.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :shop %><br>
    <%= form.text_field :shop %>
    <% @location.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :quest %><br>
    <%= form.text_field :quest %>
    <% @location.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Location Modification</h1>

<h1><%= @location.name %></h1>

<%= render "form", location: @location %>

<li><%= link_to "Destroy", location_path(@location), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>

app/views/locations/index.html.erb
<h1>Last of the Fallen Locations</h1>

<ul>
    <% @locations.each do |location| %>
        <li>
            <%= link_to location.name, location %>
        </li>
    <% end %>
</ul>

app/views/locations/new.html.erb
<h1>Location Creation</h1>

<%= form_with model: @location do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% @location.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

    <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/show.html.erb
<h1><%= @location.name %></h1>

<h1><%= @location.shop %></h1>

<h1><%= @location.quest %></h1>

<h1><%= @location.bank %></h1>

<li><%= link_to "Map", locations_path %></li>

app/views/units/_form.html.erb
<%= form_with model: unit do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% unit.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :classtype %><br>
    <%= form.select :classtype, ['warrior', 'ranger', 'mage'], selected: 'warrior' %>
  </div>

  <div>
    <%= form.label :gender %><br>
    <%= form.select :gender, ['male', 'female'], selected: 'male' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Unit Modification</h1>

<%= render "form", unit: @unit %>

app/views/units/index.html.erb
<h1>Last of the Fallen</h1>

<ul>
    <% @units.each do |unit| %>
        <li>
            <%= link_to unit.name, unit %>
        </li>
    <% end %>
</ul>

<div class = "create"><%= link_to "New Character", new_unit_path %></div><br/>
<%= link_to "New Location", new_location_path %>

app/views/units/new.html.erb
<h1>Unit Creation</h1>

<%= render "form", unit: @unit %>

app/views/units/show.html.erb
<h1><span class="charHead">Name:</span> <span class="charStat"><%= @unit.name %></span></h1>

<p><span class="charHead">Class:</span> <span class="charStat"><%= @unit.classtype %></span></p>

<p><span class="charHead">HP:</span> <span class="charStat"><%= @unit.char_hp %></span></p>

<p><span class="charHead">TP:</span> <span class="charStat"><%= @unit.char_tp %></span></p>

<p><span class="charHead">LVL:</span> <span class="charStat"><%= @unit.char_lvl %></span></p>

<p><span class="charHead">XP:</span> <span class="charStat"><%= @unit.char_xp %></span></p>

<p><span class="charHead">ATP:</span> <span class="charStat"><%= @unit.char_atp %></span></p>

<p><span class="charHead">DEF:</span> <span class="charStat"><%= @unit.char_def %></span></p>

<p><span class="charHead">EVA:</span> <span class="charStat"><%= @unit.char_eva %></span></p>

<p><span class="charHead">GOLD:</span> <span class="charStat"><%= @unit.gold %></span></p>

<ul>
  <li><%= link_to "Map", locations_path %></li>
  <li><%= link_to "Edit", edit_unit_path(@unit) %></li>
  <li><%= link_to "Destroy", unit_path(@unit), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>